### ISSUE TITLE
document fix (VersionControl_Git_Object_Commit::getCreatedAt()/getCommittedAt())

### ISSUE THREAD

**Issue by hidenorigoto** [pear/VersionControl_Git#10]
VersionControl_Git_Object_Commit::getCreatedAt()/getCommittedAt() returns timestamp (int) value, so the example of these methods should be fixed.

Current example is as follows:

var_dump($commits[0]->getCreatedAt());
/*
object(DateTime)#5 (3) {
}
*/

**Comment by cweiske** [comment]
Also fixed in the pear documentation sources.
