### ISSUE TITLE
Adding a tag for composer support 

### ISSUE THREAD

**Issue by kmelia** [pear/VersionControl_Git#14]
Hi,
When you get the package "pear/versioncontrol_git" with composer it is always more simple and fast to get a tag instead of dev-master.
Can you create a tag and publish it on https://packagist.org/ ?

P.S : there is the same issue on https://github.com/pear/PEAR_Exception/issues/3, can you relate these 2 tags ?

**Comment by NikolaySl** [comment]
+1

**Comment by giggsey** [comment]
+1

**Comment by knobsam** [comment]
+1

**Comment by fiasco** [comment]
+1

**Comment by cweiske** [comment]
0.5.0 has been tagged: https://packagist.org/packages/pear/versioncontrol_git#v0.5.0
